name: Security Checks

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run SAST with Bandit
      run: |
        bandit -r . -f json -o bandit-results.json

    - name: Run DAST with OWASP ZAP
      run: |
        # Ensure that your application is running on http://localhost:5000 during this step
        docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -g gen.conf -r zap-report.html

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: security-results
        path: |
          bandit-results.json
          zap-report.html
